### ISSUE TITLE
VS2015 + core1.1.0 无法启动debug

### ISSUE THREAD

**Issue by liguobao** [sunshine4me/ShareDevice#1]
Unable to resolve 'ImageSharp (>= 1.0.0-alpha-000335)' for '.NETCoreApp,Version=v1.0'.
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "C:\code\github\ShareDevice\.vs\restore.dg"
log  : Restoring packages for C:\code\github\ShareDevice\src\ShareDevice\project.json...
error: Unable to resolve 'ImageSharp (>= 1.0.0-alpha-000335)' for '.NETCoreApp,Version=v1.0'.
log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in C:\code\github\ShareDevice\src\ShareDevice\project.json...
log  : Lock file has not changed. Skipping lock file write. Path: C:\code\github\ShareDevice\src\ShareDevice\project.lock.json
log  : C:\code\github\ShareDevice\src\ShareDevice\ShareDevice.xproj
log  : Restore failed in 2492ms.
Errors in C:\code\github\ShareDevice\src\ShareDevice\ShareDevice.xproj
    Unable to resolve 'ImageSharp (>= 1.0.0-alpha-000335)' for '.NETCoreApp,Version=v1.0'.

我找了下这个ImageSharp，没找到对应的版本，能不能更新下？
谢谢了

**Comment by sunshine4me** [comment]
这个图片处理包是未发行版本, 需要在nuget 里添加nuget程序包源:
ImageSharp
https://www.myget.org/F/imagesharp

**Comment by liguobao** [comment]
好的，非常感谢，我稍后试一下。
